### PR TITLE
REC-28: Hasura auth0 sync

### PR DESCRIPTION
**Pull request by akshaysharma21**
- added auth0 rules in the auth0 folder;
- added .env file and included it in gitignore
- using the .env file to store sensitive data locally

### CODE REVIEW

**Comment by James-Firth** [comment]
You'll need to run `pnpm add` for those new dependencies and push the updated `pnpm-lock.json` file for checks to pass. Ping me when you do and I'll review!

**Review by Musical-Bonesie — COMMENTED** [review]
In auth0/rules/sync-user.js on line 17, would it be beneficial to name that variable something more descriptive like userInfo or something like that? 

- Is the console.log on line 27 needed? 

-- A "nice to have" is an .env.sample with example environment variables I would need to run/test this branch out! 😎

image

**Comment by akshaysharma21** [comment]
> In auth0/rules/sync-user.js on line 17, would it be beneficial to name that variable something more descriptive like userInfo or something like that?
> 
> * Is the console.log on line 27 needed?
> 
> -- A "nice to have" is an .env.sample with example environment variables I would need to run/test this branch out! 😎
> 
> image

Good idea. I renamed the var to query_variables because variables is a standard graphql term so I felt like it should be there. Good catch with the log and the sample. I committed a .env.sample file that is supposed to indicate where the file goes and it's structure.

**Review by James-Firth — APPROVED** [review]
Looks good to me. Since I have access to the other repo I know what to do with these files and normally I'd ask for docs, but since like you said we're short on time we can skip it.

**Pull request merged**
